### ISSUE TITLE
Mouse hover shows previous chart data

### ISSUE THREAD

**Issue by JaviBonilla** [vramosx/flutter_web_chartjs#2]
Thanks for this great package!

When I reload data in a chart and hover the mouse around, sometimes the previous data chart flashes in and out. Maybe it is related to [this issue](https://stackoverflow.com/questions/43490743/chartjs-mouse-hover-bug-showing-previous-charts).

- Any idea how to solve this?
- Another question, are you planning to support  [time cartesian axis](https://www.chartjs.org/docs/latest/axes/cartesian/time.html)?

Thnaks!

**Comment by JaviBonilla** [comment]
With respect to the axes, I made minor changes and managed to made simple examples of the linear and time axes work.

- For the time axis, the Moments.js library is needed, although Chart.js has also adapters for other date libraries.
- The linear axis is working fine without a tooltip callback, otherwise the tooltip is not shown and the charts fades while moving the cursor until it disappears. No idea, why this is happening.

**Comment by vramosx** [comment]
Hi, @JaviBonilla! 

I appreciate your support!

I fixed the issue with mouse hover in this pull request. I will close this issue just to keep organized. 

For the tooltip problem, can you please open another issue with any example? I couldn't reproduce the problem here.

> Another question, are you planning to support time cartesian axis?

I don't have any plans at the moment. I still need to implement other features of the current charts.

**Comment by JaviBonilla** [comment]
Thanks @vramosx,

Ok, I will try to prepare an example of the tooltip issue, but I added some additional code so maybe the issue is over there.

**Comment by JaviBonilla** [comment]
@vramosx,

Just to let you know that in the *index.html* of the example, this script is referenced from localhost:

```
<script src="http://localhost:5000/chartjs.wrapper.utils.js" type="application/javascript"></script>
```

**Comment by vramosx** [comment]
@JaviBonilla,

I just updated the package and fixed the js link. Thanks!

You can now use the version 0.2.3 from pub.dev.

If you need, you can reopen the issue.
