### ISSUE TITLE
SCRIPT1005: SCRIPT1005: Expected '(' 

### ISSUE THREAD

**Issue by JaviBonilla** [vramosx/flutter_web_chartjs#8]
I am getting this error on Microsoft Edge 44 (It is working fine on modern versions):

**SCRIPT1005: SCRIPT1005: Expected '(' ------------- chartjs.wrapper.utils.min.js (2,47)**

In this line of **chartjs.wrapper.utils.min.js**:

`window.chartJSWrapperPlugin=class{checkContext=async(element,selector)=>{while(element.querySelector(selector)===null){await new Promise(resolve=>setTimeout(resolve,500))}`

It seems it is expecting a '**(**' before **async**. Any idea?
Thanks!

**Comment by JaviBonilla** [comment]
This solved the problem in **chartjs.wrapper.utils.min.js**.

```window.chartJSWrapperPlugin=class{async checkContext(element,selector {while(element.querySelector(selector)===null){await new Promise(resolve=>setTimeout(resolve,500))}```

I also changed in the same file the following:

`createGradient(gradientJson,chartContext){if(gradientJson .....`
`showChart(chartId,config,formatTooltip){config=JSON.pars .....`

**Comment by JaviBonilla** [comment]
It seems that for supporting Microsoft Edge Legacy, it is also required the following in **index.html**.

`<script src="https://unpkg.com/@webcomponents/webcomponentsjs/webcomponents-loader.js"></script>`

[More info about Polymer library](https://polymer-library.polymer-project.org/3.0/docs/about_30).

**Comment by JaviBonilla** [comment]
It seems that this must be also included in **index.html** to support Microsoft Edge Legacy.

`<script src="https://cdnjs.cloudflare.com/ajax/libs/webcomponentsjs/2.3.0/webcomponents-bundle.js"></script>`

**Comment by vramosx** [comment]
Fixed with `0.2.6-beta`. Please let me know if need any change. And thanks again, Javi!
